/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab_semana6;

/**
 *
 * @author saidn
 */
public class pestana extends javax.swing.JFrame {

    String palabras[] = {"componentes", "ingenieria", "sistemas", "computadora", "java", "libreria", "swing", "programador", "sintaxis", "laboratorio"};

    /**
     * Creates new form pestana
     */
    public pestana() {
        
        initComponents();
        listaPal.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestana = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        bJugar = new javax.swing.JButton();
        bCambiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPal = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pestana.setBackground(new java.awt.Color(153, 204, 255));

        titulo.setBackground(new java.awt.Color(153, 255, 255));
        titulo.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Conocimiento de Palabras");

        bJugar.setBackground(new java.awt.Color(153, 153, 255));
        bJugar.setForeground(new java.awt.Color(0, 0, 0));
        bJugar.setText("Jugar");
        bJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bJugarActionPerformed(evt);
            }
        });

        bCambiar.setBackground(new java.awt.Color(153, 153, 255));
        bCambiar.setForeground(new java.awt.Color(0, 0, 0));
        bCambiar.setText("Cambiar");
        bCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lista de Palabras");

        jScrollPane1.setViewportView(listaPal);

        javax.swing.GroupLayout pestanaLayout = new javax.swing.GroupLayout(pestana);
        pestana.setLayout(pestanaLayout);
        pestanaLayout.setHorizontalGroup(
            pestanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanaLayout.createSequentialGroup()
                .addGroup(pestanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestanaLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pestanaLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(pestanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pestanaLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        pestanaLayout.setVerticalGroup(
            pestanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestanaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(bJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        getContentPane().add(pestana, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 660, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJugarActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_bJugarActionPerformed

    void actualizarlista() {
        String[] textoLista = new String[palabras.length];

        for (int i = 0; i < palabras.length; i++) {
            textoLista[i] = (i + 1) + "." + palabras[i];
        }
        listaPal.setListData(textoLista);

    }


    private void bCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarActionPerformed
        bJugar.setVisible(false);
        bCambiar.setVisible(false);
        titulo.setVisible(false);
listaPal.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_bCambiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pestana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pestana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pestana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pestana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new pestana().setVisible(true);
                    
            }
        });
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCambiar;
    private javax.swing.JButton bJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JList<String> listaPal;
    private static javax.swing.JPanel pestana;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
